services:
  - docker
  
env:
  DOCKER_COMPOSE_VERSION: 1.4.2

script:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo cp docker-compose /usr/local/bin
  - ./docker-composer up
