version: '2'
services:

  apache:
    image: rafaelcgstz/magento2
    ports:
        - "80:80"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./magento2:/var/www/html
      # Example of my MacOS config
      # - /Users/rafaelcgstz/Public/Develop:/var/www/html
      - ~/.composer/auth.json:/root/.composer/auth.json

  db:
    image: mariadb
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
