version: '2'
services:
  apache:
    build: .
    ports:
      - "88:80" # web
      - "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - <project_name>-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=10.254.254.254"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - <project_name>-network

  db:
    image: mariadb
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <project_name>-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=magento
     - PMA_PASSWORD=magento
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
     - 6379:6379
    networks:
      - <project_name>-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
