#!/usr/bin/env bash
docker-compose -f docker-compose.yml -f docker-compose.elasticsearch.yml up -d

echo "
===================== 🚀 Done 🚀 ===================
      Access your new links:

      🌎 Web server: http://localhost/
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
